services:
  db:
    image: mysql:latest
    container_name: game-tracker-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game-tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
